#*END

[config]
    DebugLevel = "1"
    MaxInstances = "4"
    WaitTime = "100"

[eserv]
    Port = "2225"
    Server = "192.168.1.229"

[path]
    LocalSocketPath = "/opt/MicroWorld/var/run/winclient"
    WinClientpidPath = "/opt/MicroWorld/var/run/winclient.pid"
